### PR TITLE
split deploy scripts

### PR DESCRIPTION
**Pull request by hxquangnhat**
move deploy scripts from zoe-devel to here
update document (install.rst) to README.MD
changes will be made on zoe-devel (update docs, remove deploy folder) after this PR is merged to master

### CODE REVIEW

**Review by dvenza — APPROVED** [review]
LGTM

**Comment by hxquangnhat** [comment]
I could leave the manually installation here or I need to remove it too?

**Comment by dvenza** [comment]
I think it's better to remove it, to keep only one copy of each part. Otherwise it gets difficult to keep all the pieces updated.
What do you think?

Thanks
Daniele

**Comment by hxquangnhat** [comment]
Yes, I think so. I'll remove them in this repo.

**Pull request merged**
